name: Build and Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Install dependencies
        run: yarn install
        working-directory: appl

      - name: Build WASM andNext.js app
        run: yarn build
        working-directory: appl

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: appl

      - name: Build output for Vercel (optional, if not done above)
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: appl

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: appl
